services:
  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "C:/mongo/data:/data/db"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  bff:
    build: ./bff
    container_name: bff
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - messagesService
    networks:
      - app-network

  messagesService:
    build: ./microservices/messageService
    container_name: MessageService
    ports:
      - "4003:4003"
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge